[project]
name = "udp-hijack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
pretty = [
    "rich>=13.9.4",
]

[dependency-groups]
dev = [
    "ruff>=0.9.2",
]
