[project]
name = "msu-ssc"
dynamic = ["version"]
description = "Morehead State University Space Science Center utilities"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "python-json-logger>=3.0.1",
    "rich>=13.8.1",
]
license = "MIT"
license-files = [ "LICENSE" ]
authors = [
    {name = "David Mayo", email = "dcmayo@moreheadstate.edu"},
]

[project.urls]
homepage = "https://github.com/msu-ssc/msu-ssc"

[project.optional-dependencies]

[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]>=6.3.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# write_to = "src/blah2/_version.py"
# version_file = "src/blah2/_version.txt"
version_scheme = "only-version"
local_scheme = "no-local-version"
fallback_version = "0.0.0"
tag_regex = "^(\\d+\\.\\d+\\.\\d+)$"

[dependency-groups]
dev = [
    "freezegun>=1.5.1",
    "pytest>=7.4.4",
    "ruff>=0.9.5",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
    "F541", # f-string without any placeholders
]
extend-select = [
    "I001", # isort unsorted-imports
]

[tool.ruff.lint.isort]
force-single-line = true


[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401", # imported but unused
]
